

ALTER TABLE S004.EBB_MODULES
DROP PRIMARY KEY CASCADE;

DROP TABLE S004.EBB_MODULES CASCADE CONSTRAINTS;

CREATE TABLE S004.EBB_MODULES
(
  MODULE_ID        NUMBER,
  MODULE_NAME      VARCHAR2(1000 BYTE),
  MODULE_URL       VARCHAR2(1000 BYTE), 
  MODULE_GROUP_ID  NUMBER,      
  SEQ_NO           NUMBER,
  CREATED_BY       VARCHAR2(50 BYTE)            DEFAULT user,
  DATE_CREATED     DATE                         DEFAULT sysdate,
  MODIFIED_BY      VARCHAR2(50 BYTE),
  DATE_MODIFIED    DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.EBB_MODULES IS 'EBB MODULES';


CREATE UNIQUE INDEX S004.EBB_MODULES_PK ON S004.EBB_MODULES
(MODULE_ID)
LOGGING
TABLESPACE HRIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX S004.EBB_MODULES_UK ON S004.EBB_MODULES
(MODULE_NAME)
LOGGING
TABLESPACE HRIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM EBB_MODULES;

CREATE PUBLIC SYNONYM EBB_MODULES FOR S004.EBB_MODULES;


ALTER TABLE S004.EBB_MODULES ADD (
  CONSTRAINT EBB_MODULES_PK
 PRIMARY KEY
 (MODULE_ID)
    USING INDEX 
    TABLESPACE HRIS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT EBB_MODULES_UK
 UNIQUE (MODULE_NAME)
    USING INDEX 
    TABLESPACE HRIS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


