ALTER TABLE S004.S004_MODULE_TESTS
DROP PRIMARY KEY CASCADE;

DROP TABLE S004.S004_MODULE_TESTS CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_MODULE_TESTS
(
  TEST_ID          NUMBER,
  TEST_DATE        DATE,
  MODULE_ID        NUMBER,
  FINDING_DESC     VARCHAR2(4000),
  FINDING_TYPE     VARCHAR2(10),
  ACTED_DATE       DATE,
  CURR_STATUS      VARCHAR(10),
  CREATED_BY       VARCHAR2(50 BYTE)            DEFAULT user,
  DATE_CREATED     DATE                         DEFAULT sysdate,
  MODIFIED_BY      VARCHAR2(50 BYTE),
  DATE_MODIFIED    DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_MODULE_TESTS IS 'HRIS MODULE_TESTS';


