DROP TABLE S004.S004_T08005 CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_T08005
(
  SEQ_NO         NUMBER,
  VACCINE_CODE   NUMBER,
  VACCINE_NAME   VARCHAR2(1000 BYTE),
  FREQUENCY      NUMBER,
  REMARKS        VARCHAR2(1000 BYTE),
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T08005 IS 'Maintenance Table for Vaccines';


/


