drop table S004_T07013;

  CREATE TABLE "S004"."S004_T07013" 
   ( 
   "TRAN_NO"         NUMBER, 
   "TRAN_YEAR"       DATE, 
   "ID_NO"           NUMBER, 
   "EMPL_TYPE"       VARCHAR2(10), 
   "TRN_TYPE"        VARCHAR(1), 
   "CONV_CODE"       NUMBER, 
   "BUDGET_AMT"      NUMBER, 
   "COST_CENTER"     NUMBER, 
   "REMARKS"         VARCHAR2(1000), 
   "CREATED_BY"      VARCHAR2(100), 
   "DATE_CREATED"    DATE, 
   "MODIFIED_BY"     VARCHAR2(100), 
   "DATE_MODIFIED"   DATE
   )   
   PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HRIS";
  
 COMMENT ON TABLE S004.S004_T07013 IS 'TRAINING BUDGET';
