DROP TABLE S004.S004_MODULE_PROCS;

ALTER TABLE S004.S004_MODULE_PROCS
DROP PRIMARY KEY CASCADE;

DROP TABLE S004.S004_MODULE_PROCS CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_MODULE_PROCS
(
  MODULE_PROC_ID   NUMBER,
  MODULE_ID        NUMBER,
  PROC_ID          NUMBER,
  TABLE_VIEW       VARCHAR2(100),
  CREATED_BY       VARCHAR2(50 BYTE)            DEFAULT user,
  DATE_CREATED     DATE                         DEFAULT sysdate,
  MODIFIED_BY      VARCHAR2(50 BYTE),
  DATE_MODIFIED    DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_MODULE_PROCS IS 'HRIS MODULE_PROCS';

CREATE UNIQUE INDEX S004.S004_MODULE_PROCS_UK ON S004.S004_MODULE_PROCS
(MODULE_ID, PROC_ID)
LOGGING
TABLESPACE HRIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM S004_MODULE_PROCS;

CREATE PUBLIC SYNONYM S004_MODULE_PROCS FOR S004.S004_MODULE_PROCS;


ALTER TABLE S004.S004_MODULE_PROCS ADD (
  CONSTRAINT S004_MODULE_PROCS_UK
 UNIQUE (MODULE_ID, PROC_ID)
    USING INDEX 
    TABLESPACE HRIS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


