DROP TABLE S004.S004_T08012 CASCADE CONSTRAINTS;
DROP TRIGGER S004_T08012_BI001;

CREATE TABLE S004.S004_T08012
(
  TRAN_NO         NUMBER,
  TRAN_DATE       DATE,
  ID_NO           NUMBER,
  AGE_BRAK_CODE   NUMBER,
  EMPL_TYPE       VARCHAR2(2 BYTE),
  COST_CENTER     VARCHAR2(10 BYTE),
  DEPARTMENT      VARCHAR2(10 BYTE),
  GROUP_CODE      VARCHAR2(10 BYTE),
  CLEARANCE_TYPE  NUMBER,
  SPORT_TYPE      NUMBER,
  DOCTOR_CODE     NUMBER,
  IS_CLEARED      NUMBER,
  REMARKS         VARCHAR2(4000 BYTE),
  POST_STATUS     NUMBER,
  POST_DATE       DATE,
  CREATED_BY      VARCHAR2(100 BYTE),
  DATE_CREATED    DATE,
  MODIFIED_BY     VARCHAR2(100 BYTE),
  DATE_MODIFIED   DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T08012 IS 'Clearance Transaction Table';

/


