DROP TABLE S004.S004_MODULE_PROC_OBJ;

ALTER TABLE S004.S004_MODULE_PROC_OBJ
DROP PRIMARY KEY CASCADE;

DROP TABLE S004.S004_MODULE_PROC_OBJ CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_MODULE_PROC_OBJ
(
  MODULE_PROC_OBJ_ID  NUMBER,
  MODULE_ID           NUMBER,
  MODULE_PROC_ID      NUMBER,
  FIELD_NAME          VARCHAR2(100),
  FIELD_LABEL         VARCHAR2(100),
  DISPLAY_TYPE_ID     VARCHAR2(100),
  AUTO_COMPLETE_ID    VARCHAR2(1),
  IS_MANDATORY        VARCHAR2(1),
  IS_CHECKEXIST       VARCHAR2(1),
  CHECK_TYPE_ID       NUMBER,
  SEQ_NAME            VARCHAR2(100),
  CREATED_BY          VARCHAR2(50 BYTE)            DEFAULT user,
  DATE_CREATED        DATE                         DEFAULT sysdate,
  MODIFIED_BY         VARCHAR2(50 BYTE),
  DATE_MODIFIED       DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_MODULE_PROC_OBJ IS 'HRIS MODULE_PROC_OBJ';

CREATE UNIQUE INDEX S004.S004_MODULE_PROC_OBJ_UK ON S004.S004_MODULE_PROC_OBJ
(MODULE_ID, MODULE_PROC_ID, FIELD_NAME)
LOGGING
TABLESPACE HRIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP PUBLIC SYNONYM S004_MODULE_PROC_OBJ;

CREATE PUBLIC SYNONYM S004_MODULE_OBJ FOR S004.S004_MODULE_PROC_OBJ;


ALTER TABLE S004.S004_MODULE_PROC_OBJ ADD (
  CONSTRAINT S004_MODULE_PROC_OBJ_UK
 UNIQUE (MODULE_ID, MODULE_PROC_ID, FIELD_NAME)
    USING INDEX 
    TABLESPACE HRIS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
