DROP TABLE S004.S004_T07019 CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_T07019
(
  TRACKER_SEQNO       NUMBER,
  TRACKER_DESC        VARCHAR2(500 BYTE),
  USER_CODE           VARCHAR2(500 BYTE),
  NEXT_TRACKER_SEQNO  VARCHAR2(50 BYTE),
  REMARKS             VARCHAR2(4000 BYTE),
  CREATED_BY          VARCHAR2(100 BYTE)        DEFAULT user,
  DATE_CREATED        DATE                      DEFAULT sysdate,
  MODIFIED_BY         VARCHAR2(100 BYTE),
  DATE_MODIFIED       DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T07019 IS 'TRAINING REQUEST TRACKER REFERENCE';
/



