DROP TABLE S004.S004_T08010_PHILHEALTH CASCADE CONSTRAINTS;
DROP TRIGGER S004_T080010_PHL_BI001;

CREATE TABLE S004.S004_T08010_PHILHEALTH
(
  LDGR_NO        NUMBER,
  ID_NO          NUMBER,
  DEPENDENT_ID   NUMBER,
  JV_TRANDATE    DATE,
  JV_NUMBER      VARCHAR2(20 BYTE),
  AMOUNT         NUMBER,
  POST_DATE      DATE,
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T08010_PHILHEALTH IS 'Medical Chart Ledger - PhilHealth Counterpart AS OF JUNE 10, 2014 - THIS FILE SI NO LONGER NEEDED SINCE THE DATA WILL BE SAVED T S004_T08010_BILLING DIRECTLY';

/


