ALTER TABLE S004.S004_T09000
 DROP PRIMARY KEY CASCADE;

DROP TABLE S004.S004_T09000 CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_T09000
(
  CCNT_CD              VARCHAR2(10 BYTE),
  CCNT_DESC            VARCHAR2(500 BYTE),
  CCNT_TYPE            VARCHAR2(1 BYTE),
  CCNT_PARENT_CCNT_CD  VARCHAR2(10 BYTE),
  CCNT_MATERIAL_TYPES  VARCHAR2(50 BYTE),
  CCNT_ABBRV           VARCHAR2(10 BYTE),
  CCNT_HEAD            VARCHAR2(500 BYTE),
  CCNT_DEPTNAME        VARCHAR2(500 BYTE),
  CCNT_STATUS          VARCHAR2(1 BYTE),
  CCNT_START_DATE      DATE,
  CCNT_END_DATE        DATE,
  CCNT_REMARKS         VARCHAR2(500 BYTE),
  CCNT_DEPT_CD         VARCHAR2(10 BYTE),
  CCNT_GROUP_CD        VARCHAR2(10 BYTE),
  CCNT_ACCT_CODE       VARCHAR2(20 BYTE),
  CREATED_BY           VARCHAR2(50 BYTE)        DEFAULT user,
  DATE_CREATED         DATE                     DEFAULT sysdate,
  MODIFIED_BY          VARCHAR2(50 BYTE),
  DATE_MODIFIED        DATE,
  SEQ_NO               NUMBER
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T09000 IS 'COST CENTER REFERENCE TABLE';


/