DROP TABLE S004.S004_T08010_VACCINE CASCADE CONSTRAINTS;
DROP TRIGGER S004_T080010_VAC_BI001;

CREATE TABLE S004.S004_T08010_VACCINE
(
  LDGR_NO        NUMBER,
  SEQ_NO         NUMBER,
  TRAN_YEAR      NUMBER,
  TRAN_DATE      DATE,
  ID_NO          NUMBER,
  DEP_ID         NUMBER,
  VACCINE_CODE   NUMBER,
  BRAND          VARCHAR2(1000 BYTE),
  ROUTE          VARCHAR2(100 BYTE),
  SITE_GIVEN     VARCHAR2(100 BYTE),
  VACCINE_LOTNO  VARCHAR2(100 BYTE),
  MANUFACTURER   VARCHAR2(1000 BYTE),
  REMARKS        VARCHAR2(4000 BYTE),
  IN_HOUSE       CHAR(1 BYTE),
  NEXT_VACCINE   DATE,
  POST_DATE      DATE,
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T08010_VACCINE IS 'Medical Chart Ledger - Vaccination';

/


