

ALTER TABLE S004.S004_MODULES
DROP PRIMARY KEY CASCADE;

DROP TABLE S004.S004_MODULES CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_MODULES
(
  MODULE_ID        NUMBER,
  MODULE_NAME      VARCHAR2(1000 BYTE),
  PROC_TYPE        VARCHAR2,
  MODULE_URL       VARCHAR2(1000 BYTE), 
  MODULE_GROUP_ID  NUMBER,
  MODULE_DESC      VARCHAR2(4000),
  PROC_DESC        VARCHAR2(4000),
  SEQ_NO           NUMBER,
  OBJ_NAME         VARCHAR2(100),
  JSON_NAME        VARCHAR2(100),
  OBJ_DELETE       VARCHAR2(100),
  CREATED_BY       VARCHAR2(50 BYTE)            DEFAULT user,
  DATE_CREATED     DATE                         DEFAULT sysdate,
  MODIFIED_BY      VARCHAR2(50 BYTE),
  DATE_MODIFIED    DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_MODULES IS 'HRIS MODULES';


CREATE UNIQUE INDEX S004.S004_MODULES_PK ON S004.S004_MODULES
(MODULE_ID)
LOGGING
TABLESPACE HRIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX S004.S004_MODULES_UK ON S004.S004_MODULES
(MODULE_NAME)
LOGGING
TABLESPACE HRIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM S004_MODULES;

CREATE PUBLIC SYNONYM S004_MODULES FOR S004.S004_MODULES;


ALTER TABLE S004.S004_MODULES ADD (
  CONSTRAINT S004_MODULES_PK
 PRIMARY KEY
 (MODULE_ID)
    USING INDEX 
    TABLESPACE HRIS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
               
ALTER TABLE S004.S004_MODULES ADD CONSTRAINT S004_MODULES_URL
 UNIQUE (MODULE_URL)
    USING INDEX 
    TABLESPACE HRIS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               );


