DROP TABLE S004.S004_T08015 CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_T08015
(
  TRAN_NO        NUMBER,
  TRAN_DATE      DATE,
  ID_NO          NUMBER,
  AGE_BRAK_CODE  NUMBER,
  EMPL_TYPE      VARCHAR2(2 BYTE),
  COST_CENTER    VARCHAR2(10 BYTE),
  DEPARTMENT     VARCHAR2(10 BYTE),
  GROUP_CODE     VARCHAR2(10 BYTE),
  MEDPLAN_TYPE   VARCHAR2(2 BYTE),
  MEDPLAN_CODE   VARCHAR2(2 BYTE)               DEFAULT 2,
  SKED_CODE      NUMBER,
  MEDS_CODE      NUMBER,
  MEDS_QTY       NUMBER,
  RELEASED_DATE  DATE,
  MAINT_STATUS   NUMBER,
  POST_STATUS    NUMBER,
  POST_DATE      DATE,
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T08015 IS 'Employees with Medicine Maintenance Transaction Table';



