DROP TABLE S004.S004_T08009 CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_T08009
(
  DS_CODE        NUMBER,
  DS_DESC        VARCHAR2(1000 BYTE),
  DS_TYPE        NUMBER,
  DS_RATE        NUMBER,
  REMARKS        VARCHAR2(1000 BYTE),
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T08009 IS 'Maintenance Table for Dental Services';

COMMENT ON COLUMN S004.S004_T08009.DS_TYPE IS '0 = Free  
1 = with charge';


/


