DROP TABLE S004.S004_T08001 CASCADE CONSTRAINTS;

CREATE TABLE S004.S004_T08001
(
  ID_NO           NUMBER,
  EMPL_TYPE       VARCHAR2(2 BYTE),
  COST_CENTER     VARCHAR2(10 BYTE),
  DEPARTMENT      VARCHAR2(10 BYTE),
  GROUP_CODE      VARCHAR2(10 BYTE),
  PLAN_COVERAGE   NUMBER,
  PLAN_CURR_BAL   NUMBER,
  PLAN_AVAIL_BAL  NUMBER,
  AVAIL_APE       CHAR(1 BYTE),
  AVAIL_ADE       CHAR(1 BYTE),
  AVAIL_EYEGLASS  CHAR(1 BYTE),
  ALLERGIES       VARCHAR2(4000 BYTE),
  REMARKS         VARCHAR2(4000 BYTE),
  CREATED_BY      VARCHAR2(100 BYTE),
  DATE_CREATED    DATE,
  MODIFIED_BY     VARCHAR2(100 BYTE),
  DATE_MODIFIED   DATE,
  SEQ_NO          NUMBER
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.S004_T08001 IS 'Employee Masterfile Medical Plan Coverage Table';


/


