DROP TABLE S004.ERRORS;

CREATE TABLE S004.ERRORS
(
  ERROR_NO       NUMBER,
  URL            VARCHAR2(4000 BYTE),
  ERROR_MESSAGE  VARCHAR2(4000 BYTE),
  OCCURENCE      NUMBER,
  ERROR_TYPE     VARCHAR2(1),   
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE S004.ERRORS IS 'Maintenance Table for ERRORS';


/


